server:
  port: 9004
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #配置nacos地址
management:
  endpoint:
    web:
      exposure:
        include: '*' ##监控的断点全部打开

