server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #配置nacos地址
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=UTC
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false
##监控的断点全部打开
#management:
#  endpoint:
#    web:
#      exposure:
#        include: '*'
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true