server:
  port: 2003
spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
        #自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?serverTimezone=UTC
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false
##监控的断点全部打开
#management:
#  endpoint:
#    web:
#      exposure:
#        include: '*'
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true