server:
  port: 84
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #配置nacos地址
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719


#消费者将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel 对feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoint:
    web:
      exposure:
        include: '*' ##监控的断点全部打开